version: '3'
services:
  server:
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    build: ./
    image: server
    container_name: dart_srv
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    restart: always
    image: "mongo"
    container_name: 'mongodb'
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
    driver: local
